### PR TITLE
Switch to gradle-execfork-plugin

### PR DESCRIPTION
**Pull request by mr-july**
The implementation is as proposed in the [issue #36](https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/36).
Resolves springdoc/springdoc-openapi-gradle-plugin#28, resolves springdoc/springdoc-openapi-gradle-plugin#63, resolves springdoc/springdoc-openapi-gradle-plugin#67

### CODE REVIEW

**Comment by bnasslahsen** [comment]
Thank you @mr-july for your great contribution to the project.

**Comment by davidconnard** [comment]
Hey there, yes, great contributions, and thanks @bnasslahsen for merging this!

Any idea when we can get a new release cut?  The current release is still `1.3.3` which that predates these changes.  The top-level project README now contains instructions that don't actually work.

**Comment by bnasslahsen** [comment]
https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/28#issuecomment-1026045261

**Comment by BernhardPosselt** [comment]
Sorry for asking here (since there are no migration docs): how do you replace with forkProperties

**Comment by rvinzent** [comment]
In addition to the outdated documentation, the removal of `forkProperties` was a breaking change and released behind a _patch_ version bump. This change should have been released behind a major bump, or maintained backwards compatibility with `forkProperties`

**Pull request merged**
