### PR TITLE
Regenerate the OpenAPI if the source files of the `bootRun` task change

### LINKED ISSUE #25: File is not overwritten unless explicitly removed first
Running with

```
    openApi {
        apiDocsUrl.set("http://localhost:8080/v3/api-docs.yaml")
        outputDir.set(file("$projectDir/doc"))
        outputFileName.set("swagger.yaml")
    }
```

and changing some content does not result in changes to the `swagger.yaml` file unless the file is explicitly rm'd first.

The default location (i.e. `build/openapi.json`) can be worked around as `gradle clean` wipes it out, but what to do with a custom location e.g. in `doc/` dir for check in to source control

### LINKED ISSUE #106: generateOpenApiDocs is wrongly considered as "up-to-date" by gradle 8.0
Hi, 

With gradle 8.0.2 and the version 1.6.0 of this plugin, I have experienced the following issue:

1.  I run ```$ ./gradlew generateOpenApiDocs``` and the openApi.json file is correctly generated.
2. I then change the source code of one of my .java files (for example the URL of one of my @RestController)
4. Running again ```$ ./gradlew generateOpenApiDocs``` does not re-generate the openApi.json, because the task is wrongly considered as "up-to-date" by gradle. 

In fact, the only way I found to regenerate the openApi.json file is to delete the existing file before regenerating it. 
Is that a known issue ?

Thanks for all.

### LINKED ISSUE #107: generateOpenApiDocs is wrongly considered as "up-to-date" by gradle 8.0
Hi,

With gradle 8.0.2 and the version 1.6.0 of this plugin, I have experienced the following issue:

1. I run  ```$ ./gradlew generateOpenApiDocs```  and the openApi.json file is correctly generated.
2. I then change the source code of one of my .java files (for example the URL of one of my @RestController)
3. Running again ```$ ./gradlew generateOpenApiDocs``` does not re-generate the openApi.json, because the task is wrongly considered as "up-to-date" by gradle. 

The actual solution to my problem is to delete the current openApi.json file ( ```$ ./gradlew clean``` can be tuned to do the trick) before running the ```$ ./gradlew generateOpenApiDocs``` task again. However, **this is not an optimal behaviour**. 

I would like to automate the following build pipeline on a project:
1. Compiling a spring boot MVC application.
2. Running generateOpenApiDocs to build an openApi.json file from it.
3. Generate a TypeScript client from the openApi.json file, using the [openAPI Generator](https://openapi-generator.tech) project.
4.  Compile the client (Typescript) application.

 I want all of the above to be executed when I run the gradlew ```build``` task, and I do not want to have to wonder if I need to run the ```clean``` task before that. (And I do not want to run it all the time for efficiency.)

Thus, I'm wondering if it is possible for you to change the conditions that makes gradle consider the generateOpenApiDocs task to be up to date ? Perhaps you can be inspired by the gradle ```compile``` task from the official java plugin. This task is run only when the source code did change.  Such a behaviour for the generateOpenApiDocs task would be really great ! 

I hope I have convinced you of the usefulness of this fix.

Thanks for your time.

### LINKED ISSUE #123: Setting task dependency leads to settings being ignored
### Description of the problem
Since [the docs](https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/fff1285081defcf4864f4c7ec1007ff551b08f4e/README.md#how-the-plugin-works) recommend to always execute `gradle clean generateOpenApiDocs`, it seems sensible to configure the appropriate task dependencies, so that `clean` is always automatically executed before `generateOpenApiDocs`. However, with version 1.7.0 this leads to custom settings being ignored.

### Example project

Link: https://github.com/rechvs/springdoc-openapi-gradle-plugin-Issue123

The project declares a task dependency (Gradle Kotlin DSL):
```kotlin
tasks {
  withType(OpenApiGeneratorTask::class.java) {
    dependsOn(clean)
  }
}
```
Additionally, the project uses the following extension settings:
```kotlin
openApi {
  outputDir = projectDir.resolve("openapi")
  outputFileName = "my-openapi.json"
}
```
### Expected result
The `generateOpenApiDocs` task generates the file `openapi/my-openapi.json`.

### Actual result
The `generateOpenApiDocs` task generates the file `build/openapi.json`, i.e., the custom settings for `outputDir` and `outputFileName` are ignored.

### LINKED ISSUE #131: Is there any way to set it so that the output file is overwritten when you build?
Is there any way to set it so that the output file is overwritten when you build? I use this:

```
openApi {
	outputFileName.set("openapi.yaml")
}
```

I noticed that it won't overwrite the yaml file if there is already one there with the same name.

### PR DESCRIPTION
**Pull request by hiddewie**
This pull request configures the task inputs of the OpenAPI generation task to match the inputs of the Spring Boot  (`bootRun`) task.

This pull request removes the need to run the Gradle `clean` task before generating the OpenAPI file. Removing the need for running `clean` makes builds quicker and matches the Gradle semantics of task authoring (see https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_outcomes)

Two tests have been added that verify the Gradle behaviour concerning caching and rerunning of tasks:
- If the same build is rerun, the task should output up to date.
- If the source files change, the OpenAPI should be regenerated. 

Docs about task inputs in https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:developing_tasks

References to other issues and pull requests that are the same problem:
- Fixes https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/106
- Fixes https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/107
- Replaces https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/140 (clean task is no longer needed if rerunning the plugin will automatically regenerate the OpenAPI file)
- Fixes https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/131
- Fixes https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/123
- Fixes https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/25

### CODE REVIEW

**Comment by bnasslahsen** [comment]
@hiddewie,

Changes merged to master.
You can test with the latest version.

**Comment by bnasslahsen** [comment]
@hiddewie,

Can you check the following test: 	fun `running the same build keeps the OpenAPI task up to date`(), as it's failing

**Comment by hiddewie** [comment]
Hi @bnasslahsen. Thanks for merging. For me the test succeeds. I am building with Java 17. I will try to reproduce the failing test.

**Comment by hiddewie** [comment]
@bnasslahsen The original PR was merged without removing the `clean` task from the default Gradle arguments it seems.

See https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/147/files#diff-0a1f1b890191dd57b7ec675f9a8b3ec0a6428b7048e5906dd9a8b56e371766acL447.

I removed the `clean` task because this is not needed and breaks efficient Gradle runs when inputs did not change.

**Comment by bnasslahsen** [comment]
@hiddewie,

Thank you for the fix!

**Comment by hosamaly** [comment]
Thanks for the fix, @hiddewie. Is it ready to be released, @bnasslahsen?

(v1.9.0 was released just one day before this was merged.)

**Comment by hosamaly** [comment]
Thanks for the fix!
~Can we get a release for this, please, @bnasslahsen?~

Apologies for the noise. Looks like the fix was merged in v1.9.0 and it was only a test that wasn't. My bad. Thank you.

**Pull request merged**
